### ISSUE TITLE
Gatsby下依赖安装Cannot find module sharp & 'vips/vips8' file not found

### ISSUE THREAD

**Issue by rayliao** [rayliao/blog#3]
Gatsby下使用`gatsby-plugin-mainfest`，安装依赖成功之后运行报错：

```
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

重新安装之后发现卡在`info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-darwin-x64.tar.gz`，无法下载，后来发现是网络问题，切换代理之后可以了。如果是从缓存获取不行的话，就清除掉缓存文件重新试。

下载之后还有一个错误：

```
throw err;
          ^

Error: write EPROTO
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
```

网上找了下，解决方案：

```
$ brew install vips --with-webp --with-graphicsmagick
$ rm -rf node_modules
$ yarn install
```

然而：`Error: invalid option: --with-webp`

然后看了两个issues：

- https://github.com/libvips/libvips/issues/1204
- https://github.com/Homebrew/homebrew-core/pull/36700

不是非常理解，好像说是没什么人通过那些方式安装，所以去掉了那些途径，我用`brew info -v vips`查了下安装情况，确实加参数的占比很低，不管了就尝试下直接`brew install vips`是否可行。

then

```
Error: Your Xcode (10.0) is too outdated.
Please update to Xcode 10.2.1 (or delete it).
Xcode can be updated from the App Store.

Error: Xcode alone is not sufficient on Mojave.
Install the Command Line Tools:
  xcode-select --install
```

继续解决，升级了`Xcode`，执行了`xcode-select --install`，继续尝试安装vips，然后安装报错：
```
==> Pouring python-3.7.4_1.mojave.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
```

至此，放弃不想折腾了。

**Comment by rayliao** [comment]
```
error /Users/LiaoYingRay/Projects/github/rayliao.github.io/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /Users/LiaoYingRay/Projects/github/rayliao.github.io/node_modules/sharp
Output:
info sharp Using cached /Users/LiaoYingRay/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
ERR! sharp Please delete /Users/LiaoYingRay/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.10.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/LiaoYingRay/Projects/github/rayliao.github.io/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/LiaoYingRay/.node-gyp/12.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/LiaoYingRay/.node-gyp/12.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/LiaoYingRay/.node-gyp/12.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/LiaoYingRay/Projects/github/rayliao.github.io/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/LiaoYingRay/Projects/github/rayliao.github.io/node_modules/sharp
```
